version: '3'
services:
  server:
    build: .
    entrypoint: ["python3", "server.py"]
    networks:
      ctf_net:
        ipv4_address: 10.123.45.3

  firewall:
    build: .
    cap_add:
      - NET_ADMIN
    entrypoint: ["python3", "firewall.py"]
    sysctls:
      - net.ipv4.ip_forward=1
    networks:
      ctf_net:
        ipv4_address: 10.123.45.4

networks:
  ctf_net:
    driver: bridge
    ipam:
      config:
        - subnet: 10.123.45.0/24